name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: jest tests
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: deploy Heroku app
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mighty-escarpment-70911"
          heroku_email: "aubrey.nicoll@gmail.com"
          healthcheck: "https://mighty-escarpment-70911.herokuapp.com/healthcheck"
          checkstring: "OK"
          rollbackonhealthcheckfailed: true